language: php

php: [5.3.3, 5.3, 5.4, 5.5, hhvm]

matrix:
  allow_failures:
      - php: hhvm

cache:
  directories:
      - vendor

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script: ./bin/phpspec run -fpretty
